### ISSUE TITLE
This is super cool!!

### ISSUE THREAD

**Issue by samertm** [Charlesetc/abstract#1]
:D

When writing my first parser, I really struggled with what the AST types should look like. I ended up generating a 1000 line file with all of the types I needed (https://github.com/samertm/chompy/blob/master/parse/nodes.go), which was a gigantic mess and made the next phase harder. I think I should have just had a single concrete Node type, like your `Abstract`.

Also, have you seen Rob Pike's video on writing a lexer in Go? It uses channels in a clever way (https://www.youtube.com/watch?v=HxaD_trXwRE), and I stole his technique for lexing multiple runes of the same type by checking them with strings.IndexRune (https://github.com/samertm/chompy/blob/master/lex/lex.go#L114).

**Comment by charlesetc** [comment]
It took me a while to get there, but yeah I like `Abstract` too. 
That talk is awesome--I think I'll try to incorporate some of his ideas too, although I'm not sure exactly how to work channels in. 
Thanks for the pull request!
